webpackJsonp_name_([1],{

/***/ "./src/app/features/lazy/index.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("Object.defineProperty(__webpack_exports__, \"__esModule\", { value: true });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"LazyModule\", function() { return LazyModule; });\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__(\"./node_modules/@angular/core/@angular/core.es5.js\");\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__angular_common__ = __webpack_require__(\"./node_modules/@angular/common/@angular/common.es5.js\");\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__angular_router__ = __webpack_require__(\"./node_modules/@angular/router/@angular/router.es5.js\");\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__lazy_actions__ = __webpack_require__(\"./src/app/features/lazy/lazy.actions.ts\");\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__lazy_routing__ = __webpack_require__(\"./src/app/features/lazy/lazy.routing.ts\");\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__lazy_component__ = __webpack_require__(\"./src/app/features/lazy/lazy.component.ts\");\n\r\n\r\n\r\n\r\n\r\n\r\nvar LazyModule = (function () {\r\n    function LazyModule() {\r\n    }\r\n    return LazyModule;\r\n}());\r\nLazyModule = __decorate([\r\n    __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__angular_core__[\"NgModule\"])({\r\n        imports: [\r\n            __WEBPACK_IMPORTED_MODULE_1__angular_common__[\"CommonModule\"],\r\n            __WEBPACK_IMPORTED_MODULE_2__angular_router__[\"RouterModule\"].forChild(__WEBPACK_IMPORTED_MODULE_4__lazy_routing__[\"a\" /* routes */]),\r\n        ],\r\n        declarations: [\r\n            __WEBPACK_IMPORTED_MODULE_5__lazy_component__[\"a\" /* LazyComponent */]\r\n        ],\r\n        providers: [\r\n            __WEBPACK_IMPORTED_MODULE_3__lazy_actions__[\"a\" /* LazyActions */]\r\n        ]\r\n    })\r\n], LazyModule);\r\n\r\n\n\n//////////////////\n// WEBPACK FOOTER\n// ./src/app/features/lazy/index.ts\n// module id = ./src/app/features/lazy/index.ts\n// module chunks = 0 1\n\n//# sourceURL=webpack:///./src/app/features/lazy/index.ts?");

/***/ }),

/***/ "./src/app/features/lazy/lazy.actions.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"a\", function() { return LazyActions; });\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__(\"./node_modules/@angular/core/@angular/core.es5.js\");\n/* tslint:disable: member-ordering */\r\n\r\nvar LazyActions = LazyActions_1 = (function () {\r\n    function LazyActions() {\r\n    }\r\n    LazyActions.prototype.decrement = function () {\r\n        return {\r\n            type: LazyActions_1.DECREMENT\r\n        };\r\n    };\r\n    LazyActions.prototype.increment = function () {\r\n        return {\r\n            type: LazyActions_1.INCREMENT\r\n        };\r\n    };\r\n    LazyActions.prototype.reset = function () {\r\n        return {\r\n            type: LazyActions_1.RESET\r\n        };\r\n    };\r\n    return LazyActions;\r\n}());\r\nLazyActions.DECREMENT = '[Lazy] Decrement';\r\nLazyActions.INCREMENT = '[Lazy] Increment';\r\nLazyActions.RESET = '[Lazy] Reset';\r\nLazyActions = LazyActions_1 = __decorate([\r\n    __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__angular_core__[\"Injectable\"])()\r\n], LazyActions);\r\n\r\nvar LazyActions_1;\r\n\n\n//////////////////\n// WEBPACK FOOTER\n// ./src/app/features/lazy/lazy.actions.ts\n// module id = ./src/app/features/lazy/lazy.actions.ts\n// module chunks = 0 1\n\n//# sourceURL=webpack:///./src/app/features/lazy/lazy.actions.ts?");

/***/ }),

/***/ "./src/app/features/lazy/lazy.component.html":
/***/ (function(module, exports) {

eval("module.exports = \"<header>\\n  <h5>\\n    This module is being loaded lazily.\\n\\n\\t\\t<div>Current Count: {{ counter | async }}</div>\\n    <button (click)=\\\"increment()\\\">Increment</button>\\n\\t\\t<button (click)=\\\"decrement()\\\">Decrement</button>\\n\\t\\t<button (click)=\\\"reset()\\\">Reset Counter</button>\\n  </h5>\\n</header>\"\n\n//////////////////\n// WEBPACK FOOTER\n// ./src/app/features/lazy/lazy.component.html\n// module id = ./src/app/features/lazy/lazy.component.html\n// module chunks = 0 1\n\n//# sourceURL=webpack:///./src/app/features/lazy/lazy.component.html?");

/***/ }),

/***/ "./src/app/features/lazy/lazy.component.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"a\", function() { return LazyComponent; });\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__(\"./node_modules/@angular/core/@angular/core.es5.js\");\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__ngrx_store__ = __webpack_require__(\"./node_modules/@ngrx/store/index.js\");\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__lazy_actions__ = __webpack_require__(\"./src/app/features/lazy/lazy.actions.ts\");\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__lazy_reducer__ = __webpack_require__(\"./src/app/features/lazy/lazy.reducer.ts\");\n\r\n\r\n\r\n\r\nvar LazyComponent = (function () {\r\n    function LazyComponent(lazyActions, store) {\r\n        this.lazyActions = lazyActions;\r\n        this.store = store;\r\n        this.counter = store.select(function (s) { return s.lazy.counter; });\r\n    }\r\n    LazyComponent.prototype.decrement = function () {\r\n        this.store.dispatch(this.lazyActions.decrement());\r\n    };\r\n    LazyComponent.prototype.increment = function () {\r\n        this.store.dispatch(this.lazyActions.increment());\r\n    };\r\n    LazyComponent.prototype.reset = function () {\r\n        this.store.dispatch(this.lazyActions.reset());\r\n    };\r\n    return LazyComponent;\r\n}());\r\nLazyComponent = __decorate([\r\n    __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__angular_core__[\"Component\"])({\r\n        selector: 'my-lazy',\r\n        template: __webpack_require__(\"./src/app/features/lazy/lazy.component.html\"),\r\n        providers: [{ provide: __WEBPACK_IMPORTED_MODULE_3__lazy_reducer__[\"a\" /* StoreWithLazy */], useFactory: __WEBPACK_IMPORTED_MODULE_3__lazy_reducer__[\"b\" /* lazyStoreFactory */], deps: [__WEBPACK_IMPORTED_MODULE_1__ngrx_store__[\"Store\"]] }]\r\n    }),\r\n    __metadata(\"design:paramtypes\", [__WEBPACK_IMPORTED_MODULE_2__lazy_actions__[\"a\" /* LazyActions */],\r\n        __WEBPACK_IMPORTED_MODULE_3__lazy_reducer__[\"a\" /* StoreWithLazy */]])\r\n], LazyComponent);\r\n\r\n\n\n//////////////////\n// WEBPACK FOOTER\n// ./src/app/features/lazy/lazy.component.ts\n// module id = ./src/app/features/lazy/lazy.component.ts\n// module chunks = 0 1\n\n//# sourceURL=webpack:///./src/app/features/lazy/lazy.component.ts?");

/***/ }),

/***/ "./src/app/features/lazy/lazy.reducer.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("/* unused harmony export lazyReducer */\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"a\", function() { return StoreWithLazy; });\n/* harmony export (immutable) */ __webpack_exports__[\"b\"] = lazyStoreFactory;\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__ngrx_store__ = __webpack_require__(\"./node_modules/@ngrx/store/index.js\");\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__reducers_index__ = __webpack_require__(\"./src/app/reducers/index.ts\");\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__lazy_actions__ = __webpack_require__(\"./src/app/features/lazy/lazy.actions.ts\");\n\r\n\r\n\r\nvar initialState = {\r\n    counter: 0\r\n};\r\nfunction lazyReducer(state, action) {\r\n    if (state === void 0) { state = initialState; }\r\n    switch (action.type) {\r\n        case __WEBPACK_IMPORTED_MODULE_2__lazy_actions__[\"a\" /* LazyActions */].DECREMENT:\r\n            return __assign({}, state, { counter: state.counter - 1 });\r\n        case __WEBPACK_IMPORTED_MODULE_2__lazy_actions__[\"a\" /* LazyActions */].INCREMENT:\r\n            return __assign({}, state, { counter: state.counter + 1 });\r\n        case __WEBPACK_IMPORTED_MODULE_2__lazy_actions__[\"a\" /* LazyActions */].RESET:\r\n            return __assign({}, state, { counter: 0 });\r\n        default:\r\n            return state;\r\n    }\r\n}\r\nvar StoreWithLazy = (function (_super) {\r\n    __extends(StoreWithLazy, _super);\r\n    function StoreWithLazy() {\r\n        return _super !== null && _super.apply(this, arguments) || this;\r\n    }\r\n    return StoreWithLazy;\r\n}(__WEBPACK_IMPORTED_MODULE_0__ngrx_store__[\"Store\"]));\r\n\r\nfunction lazyStoreFactory(appStore) {\r\n    appStore.replaceReducer(__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_1__reducers_index__[\"createNewRootReducer\"])({ lazy: lazyReducer }));\r\n    return appStore;\r\n}\r\n\n\n//////////////////\n// WEBPACK FOOTER\n// ./src/app/features/lazy/lazy.reducer.ts\n// module id = ./src/app/features/lazy/lazy.reducer.ts\n// module chunks = 0 1\n\n//# sourceURL=webpack:///./src/app/features/lazy/lazy.reducer.ts?");

/***/ }),

/***/ "./src/app/features/lazy/lazy.routing.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"a\", function() { return routes; });\n/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__lazy_component__ = __webpack_require__(\"./src/app/features/lazy/lazy.component.ts\");\n\r\nvar routes = [\r\n    {\r\n        path: '',\r\n        component: __WEBPACK_IMPORTED_MODULE_0__lazy_component__[\"a\" /* LazyComponent */]\r\n    }\r\n];\r\n\n\n//////////////////\n// WEBPACK FOOTER\n// ./src/app/features/lazy/lazy.routing.ts\n// module id = ./src/app/features/lazy/lazy.routing.ts\n// module chunks = 0 1\n\n//# sourceURL=webpack:///./src/app/features/lazy/lazy.routing.ts?");

/***/ })

});